#!/usr/bin/env python3
# ruff: noqa: E501
"""Generate deterministic Google Sans visuals for the Medium article."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets"

COMMON = """
*{box-sizing:border-box}html,body{margin:0;overflow:hidden;background:#f8fafd;color:#202124}
body{font-family:'Google Sans','Google Sans Flex',Arial,sans-serif}
.canvas{width:1600px;height:900px;padding:48px 58px;position:relative;background:linear-gradient(#edf1f5 1px,transparent 1px),linear-gradient(90deg,#edf1f5 1px,transparent 1px),#f8fafd;background-size:40px 40px}
h1{margin:0;font-size:42px;line-height:1.08;letter-spacing:-1.2px}.sub{margin-top:9px;color:#5f6368;font-size:19px}.eyebrow{font-size:13px;font-weight:750;letter-spacing:1.2px;text-transform:uppercase;color:#1967d2}.card{background:#fff;border:2px solid #dadce0;border-radius:18px;box-shadow:0 8px 22px rgba(60,64,67,.08)}.label{font-size:13px;font-weight:750;letter-spacing:.7px;text-transform:uppercase}.title{font-size:21px;font-weight:700;line-height:1.15}.body{font-size:15px;line-height:1.45;color:#5f6368}.metric{font-size:25px;font-weight:760;line-height:1.05}.pill{display:inline-block;border-radius:999px;background:#e8f0fe;color:#174ea6;padding:6px 10px;font-size:13px;font-weight:700}.blue{color:#1967d2}.green{color:#188038}.red{color:#c5221f}.amber{color:#b06000}.purple{color:#8430ce}
"""


def write(name: str, title: str, body: str, extra: str = "") -> None:
    html = f"""<!doctype html><html><head><meta charset="utf-8"><title>{title}</title><style>{COMMON}{extra}</style></head><body>{body}</body></html>"""
    (OUT / name).write_text(html)


write(
    "architecture.html",
    "ADK and Cloud Run sandbox architecture",
    """<div class="canvas"><div class="eyebrow">Reference architecture</div><h1>ADK is the control plane; the sandbox is the execution plane</h1><div class="sub">Control flow, execution, and evidence paths use compact orthogonal connectors.</div>
<div class="arch">
<svg class="links" viewBox="0 0 1484 650"><defs><marker id="a" markerWidth="7" markerHeight="7" refX="5.5" refY="2" orient="auto"><path d="M0,0 L0,4 L6,2 z" fill="#5f6368"/></marker></defs>
<path d="M214 175H330"/><path d="M550 175H610"/><path d="M850 175H1180"/><path d="M730 245V275"/><path d="M610 347H550"/><path d="M440 420V430"/><path d="M1030 492H1110V357H1180"/><path class="dash" d="M1030 535H1180"/><path class="dash blueStroke" d="M330 215H214"/>
</svg>
<div class="zone dev"><div class="zoneName blue">Developer</div></div><div class="zone host"><div class="zoneName green">Cloud Run service instance · trusted</div></div><div class="zone managed"><div class="zoneName amber">Managed services</div></div>
<div class="node web card"><div class="label blue">Interface</div><div class="title">ADK Web</div><div class="body">Prompt · events<br>function-call inspection</div></div>
<div class="node runner card"><div class="label blue">Runtime</div><div class="title">ADK Runner</div><div class="body">Session + event loop<br>streams tool results</div></div>
<div class="node agent card"><div class="label purple">Agent</div><div class="title">sandbox_pr_reviewer</div><div class="body">Gemini 3.5 Flash<br>instruction + tool registry</div></div>
<div class="node tools card"><div class="label amber">FunctionTool registry</div><div class="title">Eight fixed tools</div><div class="body">start · probe · test · patch<br>snapshot · delete · diagnostics</div></div>
<div class="node broker card"><div class="label green">Trusted broker</div><div class="title">Policy + runtime</div><div class="body">Validate ID · build argv<br>cap time + output<br>hash generated source</div></div>
<div class="sandbox"><div class="zoneName red">Native child sandbox · untrusted repository execution</div><div class="snode repo card"><div class="title">Repository process</div><div class="body">pytest · build hooks<br>generated repair</div></div><div class="snode ws card"><div class="title">/workspace</div><div class="body">Per-run bind mount<br>approved export path</div></div><div class="snode ov card"><div class="title">Ephemeral overlay</div><div class="body">Writable with --write<br>host root unchanged</div></div></div>
<div class="node gemini card"><div class="label blue">Reasoning</div><div class="title">Gemini 3.5 Flash</div><div class="body">Plans and proposes<br>never runs repo code</div></div>
<div class="node logging card"><div class="label green">Evidence</div><div class="title">Cloud Logging</div><div class="body">hash · outcome · latency</div></div>
<div class="node storage card"><div class="label purple">Optional durability</div><div class="title">Cloud Storage</div><div class="body">approved tar beyond instance</div></div>
<div class="legend"><b>Default deny:</b> public egress · parent environment · metadata server <span></span><b>Shared meter:</b> child work consumes the host instance's CPU and memory</div>
</div></div>""",
    """.arch{position:relative;height:650px;margin-top:18px}.arch .body{font-size:14px;line-height:1.34}.links{position:absolute;inset:0;width:100%;height:100%;z-index:0}.links path{fill:none;stroke:#5f6368;stroke-width:2;stroke-linejoin:round;marker-end:url(#a);opacity:.76}.links .dash{stroke-dasharray:7 7}.links .blueStroke{stroke:#4285f4}.zone{position:absolute;top:42px;height:555px;border:2px solid;border-radius:24px;background:rgba(255,255,255,.78);z-index:1}.zoneName{font-size:13px;font-weight:760;letter-spacing:1px;text-transform:uppercase}.dev{left:0;width:250px;border-color:#d2e3fc;padding:22px}.host{left:286px;width:810px;border-color:#ceead6;padding:22px}.managed{left:1130px;width:354px;border-color:#fce8b2;padding:22px}.node{position:absolute;z-index:2;padding:17px 19px}.web{left:34px;top:105px;width:180px;height:140px;border-color:#4285f4}.runner{left:330px;top:105px;width:220px;height:140px;border-color:#4285f4}.agent{left:610px;top:105px;width:240px;height:140px;border-color:#a142f4}.tools{left:610px;top:275px;width:250px;height:145px;border-color:#f9ab00}.broker{left:330px;top:275px;width:220px;height:145px;border-color:#34a853}.gemini{left:1180px;top:105px;width:260px;height:140px;border-color:#4285f4}.logging{left:1180px;top:300px;width:260px;height:115px;border-color:#34a853}.storage{left:1180px;top:460px;width:260px;height:105px;border-color:#a142f4}.sandbox{position:absolute;z-index:1;left:330px;top:430px;width:700px;height:165px;border:2px dashed #9aa0a6;border-radius:20px;background:#f8fafd;padding:15px 18px}.snode{position:absolute;top:48px;height:100px;padding:13px}.snode .body{font-size:13px}.repo{left:22px;width:200px;border-color:#ea4335}.ws{left:250px;width:190px;border-color:#34a853}.ov{left:468px;width:205px;border-color:#9aa0a6}.legend{position:absolute;z-index:2;left:286px;bottom:0;width:1154px;height:54px;border-radius:15px;background:#202124;color:#e8eaed;padding:17px 22px;font-size:14px}.legend b:first-child{color:#8ab4f8}.legend b:last-child{color:#81c995}.legend span{display:inline-block;width:55px}""",
)

write(
    "full-review-results.html",
    "Full review evidence",
    """<div class="canvas"><div class="eyebrow">Observed end-to-end result</div><h1>A real 19.10-second ADK turn — seven evidence-producing stages</h1><div class="sub">Every card is grounded in assets/evidence/full-review.json. Cards are fully contained inside the frame.</div><div class="steps">
<div class="step blueB"><b>1</b><span>START</span><strong>248.97 ms</strong><p>Detached sandbox<br>Egress denied</p></div>
<div class="step purpleB"><b>2</b><span>PROBE</span><strong>6 checks</strong><p>env=false<br>metadata=false<br>egress=false</p></div>
<div class="step redB"><b>3</b><span>BASELINE</span><strong>1,944.52 ms</strong><p>1 passed<br>3 failed</p></div>
<div class="step amberB"><b>4</b><span>PATCH</span><strong>2,309 bytes</strong><p>SHA-256<br>86e71c85cbf7…</p></div>
<div class="step greenB"><b>5</b><span>RETEST</span><strong>702.65 ms</strong><p>4 passed<br>0 failed</p></div>
<div class="step purpleB"><b>6</b><span>SNAPSHOT</span><strong>5.49 MB</strong><p>overlay.tar<br>created</p></div>
<div class="step greenB"><b>7</b><span>DELETE</span><strong>code 0</strong><p>Sandbox + workspace<br>removed</p></div>
</div><div class="boundary"><div><b>Observed boundary</b><br><span>Parent canary hidden · metadata unreachable · public egress unreachable · host-image source readable · workspace writable</span></div><div class="warning">Root write landed only in the sandbox's ephemeral <code>--write</code> overlay; the host root was not mutated.</div></div></div>""",
    """.steps{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:14px;margin-top:86px;position:relative}.steps:before{content:'';position:absolute;left:2%;right:2%;top:132px;height:5px;background:#dadce0;z-index:0}.step{position:relative;z-index:1;height:310px;border:3px solid;border-radius:20px;background:white;padding:24px 18px}.step b{display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:currentColor;color:white;font-size:16px}.step span{display:block;margin-top:24px;font-size:13px;font-weight:760;letter-spacing:1px;color:#5f6368}.step strong{display:block;margin-top:25px;font-size:20px;color:#202124}.step p{font-size:15px;line-height:1.5;color:#5f6368}.blueB{color:#4285f4}.purpleB{color:#a142f4}.redB{color:#ea4335}.amberB{color:#f9ab00}.greenB{color:#34a853}.boundary{margin-top:28px;background:#202124;border-radius:18px;padding:20px 24px;color:#e8eaed;display:grid;grid-template-columns:1.45fr 1fr;gap:30px;font-size:16px}.boundary b{color:#8ab4f8;font-size:20px}.boundary span{line-height:1.5}.warning{color:#fdd663;line-height:1.45}""",
)

write(
    "adk-agent-design.html",
    "ADK agent design",
    """<div class="canvas"><div class="eyebrow">ADK agent design</div><h1>Two controlled execution paths, one sandbox boundary</h1><div class="sub">ADK chooses a path; both paths converge on the same trusted broker and native child sandbox.</div><div class="design">
<svg viewBox="0 0 1484 610"><defs><marker id="m" markerWidth="7" markerHeight="7" refX="5.5" refY="2" orient="auto"><path d="M0,0L0,4L6,2z" fill="#5f6368"/></marker></defs>
<path d="M250 155H360"/><path d="M600 155H720"/><path d="M970 155H1100"/>
<path d="M845 230V270H530V300"/><path d="M845 270H960V300"/>
<path class="merge" d="M530 475V505H745"/><path class="merge" d="M960 475V505H745"/><path d="M745 505V530"/>
</svg>
<div class="dcard prompt card"><div class="label blue">User intent</div><div class="title">Review this repository</div><div class="body">Natural-language goal, never a shell command.</div></div>
<div class="dcard runner card"><div class="label blue">ADK Runner</div><div class="title">Session + event stream</div><div class="body">Calls the agent, records function calls/responses, exposes ADK Web.</div></div>
<div class="dcard agent card"><div class="label purple">Agent(...)</div><div class="title">Gemini 3.5 Flash</div><div class="body">Selects the next typed capability from evidence.</div></div>
<div class="dcard events card"><div class="label green">Observable result</div><div class="title">ADK events</div><div class="body">15 returned events: calls, responses, final answer.</div></div>
<div class="dcard pathA card"><div class="label amber">Path A · product workflow</div><div class="title">FunctionTool registry</div><div class="chips"><span>start</span><span>probe</span><span>test</span><span>write</span><span>snapshot</span><span>delete</span></div><div class="body">Fixed paths and commands. Model arguments: workspace_id and source_code.</div></div>
<div class="dcard pathB card"><div class="label blue">Path B · explicit code blocks</div><div class="title">Audited code_executor</div><div class="body">Direct ADK code-execution events with egress=false and a 20-second timeout.</div></div>
<div class="mergeLabel">BOTH PATHS ENTER THE SAME BROKER</div>
<div class="dcard runtime card"><div class="label red">Containment boundary</div><div class="title">SandboxRuntime → native child sandbox</div><div class="body">Validates names · constructs argv · fixes mounts/workdir · caps time/output. Prompt rules and AST checks are not containment.</div></div>
</div><div class="rule"><b>Design invariant:</b> the model chooses a capability, not the sandbox binary, host path, mount target, environment, egress flag, or raw command vector.</div></div>""",
    """.design{height:610px;position:relative;margin-top:18px}.design .body{font-size:14px;line-height:1.34}.design svg{position:absolute;inset:0;width:100%;height:100%;z-index:0}.design path{fill:none;stroke:#5f6368;stroke-width:2;stroke-linejoin:round;marker-end:url(#m);opacity:.78}.design path.merge{marker-end:none}.dcard{position:absolute;z-index:1;padding:17px 19px}.prompt{left:20px;top:85px;width:230px;height:145px;border-color:#4285f4}.runner{left:360px;top:85px;width:240px;height:145px;border-color:#4285f4}.agent{left:720px;top:85px;width:250px;height:145px;border-color:#a142f4}.events{left:1100px;top:85px;width:320px;height:145px;border-color:#34a853}.pathA{left:350px;top:300px;width:360px;height:175px;border-color:#f9ab00}.pathB{left:780px;top:300px;width:360px;height:175px;border-color:#4285f4}.chips{display:flex;flex-wrap:wrap;gap:4px;margin:9px 0}.chips span{background:#fef7e0;color:#7f4d00;border-radius:999px;padding:4px 6px;font-size:11px;font-weight:700}.mergeLabel{position:absolute;z-index:2;left:620px;top:486px;width:250px;text-align:center;font-size:11px;font-weight:760;letter-spacing:.8px;color:#5f6368;background:#f8fafd}.runtime{left:485px;top:530px;width:520px;height:100px;border-color:#ea4335;padding:15px 18px}.runtime .title{font-size:19px}.runtime .body{font-size:13px}.rule{position:absolute;left:58px;right:58px;bottom:20px;background:#202124;color:#e8eaed;border-radius:16px;padding:16px 22px;font-size:15px}.rule b{color:#8ab4f8}""",
)

write(
    "adk-test-plan.html",
    "ADK use-case test plan",
    """<div class="canvas"><div class="eyebrow">Use cases we actually test</div><h1>The same ADK agent exposes four evidence-producing paths</h1><div class="sub">Each prompt maps to a bounded tool sequence and a concrete success signal.</div><div class="cases">
<div class="case card"><div class="n blueBg">01</div><div><div class="label blue">Full repository review</div><div class="title">Can the agent repair without trusting the repo?</div><div class="seq">start → probe → test → write → retest → snapshot → delete</div><div class="body"><b>Proof:</b> 3 failures become 4 passes; snapshot exists; cleanup code 0.</div></div></div>
<div class="case card"><div class="n purpleBg">02</div><div><div class="label purple">Boundary audit</div><div class="title">Can repo code reach credentials or the network?</div><div class="seq">start → inspect_security_boundaries → delete</div><div class="body"><b>Proof:</b> parent canary false; metadata false; public egress false.</div></div></div>
<div class="case card"><div class="n greenBg">03</div><div><div class="label green">Lifecycle benchmark</div><div class="title">How fast is create + exec + delete?</div><div class="seq">benchmark_sandbox_startup(samples=30)</div><div class="body"><b>Proof:</b> 30/30 success; p50 428.347 ms; p95 455.854 ms.</div></div></div>
<div class="case card"><div class="n amberBg">04</div><div><div class="label amber">Cost planning</div><div class="title">Which meter dominates a modest workload?</div><div class="seq">estimate_monthly_cost(explicit assumptions)</div><div class="body"><b>Proof:</b> transparent $9.7954/month estimate; no sandbox runtime required.</div></div></div>
</div><div class="footerNote"><b>Failure policy:</b> tool output—not model confidence—decides whether to continue, retry, snapshot, or clean up.</div></div>""",
    """.cases{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:52px}.case{height:245px;padding:24px;display:grid;grid-template-columns:66px 1fr;gap:20px}.n{width:54px;height:54px;border-radius:15px;color:white;display:grid;place-items:center;font-size:20px;font-weight:760}.blueBg{background:#4285f4}.purpleBg{background:#a142f4}.greenBg{background:#34a853}.amberBg{background:#f9ab00}.seq{font:650 14px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;background:#f1f3f4;border-radius:10px;padding:10px 12px;margin:15px 0;color:#3c4043}.case b{color:#202124}.footerNote{margin-top:25px;background:#202124;color:#e8eaed;border-radius:16px;padding:17px 22px;font-size:16px}.footerNote b{color:#81c995}""",
)

write(
    "platform-decision-matrix.html",
    "Sandbox platform decision matrix",
    """<div class="canvas"><div class="eyebrow">Architecture decision matrix</div><h1>These sandbox products are not equivalent</h1><div class="sub">Compare isolation, state, operations, and billing—not vendor headline latency alone.</div><div class="matrix">
<div class="product cloud card"><div class="phead">Cloud Run</div><p><b>Best fit</b><br>Bursty ADK host already on Cloud Run</p><p><b>Isolation</b><br>Child sandbox inside service instance</p><p><b>State</b><br>Instance-local unless exported</p><p><b>Network</b><br>Denied by default</p><p><b>Meter</b><br>Cloud Run CPU / memory / requests</p></div>
<div class="product gke card"><div class="phead">GKE Agent Sandbox</div><p><b>Best fit</b><br>Warm pools and custom cluster policy</p><p><b>Isolation</b><br>Sandbox Pod managed by GKE</p><p><b>State</b><br>Kubernetes storage + snapshots</p><p><b>Network</b><br>Template / policy dependent</p><p><b>Meter</b><br>Nodes, control plane, storage, network</p></div>
<div class="product e2b card"><div class="phead">E2B</div><p><b>Best fit</b><br>Hosted durable sandbox sessions</p><p><b>Isolation</b><br>Vendor-managed sandbox</p><p><b>State</b><br>Pause/resume + snapshots</p><p><b>Network</b><br>Configurable</p><p><b>Meter</b><br>Per-second resources + plan</p></div>
<div class="product daytona card"><div class="phead">Daytona</div><p><b>Best fit</b><br>Rich container / VM lifecycle</p><p><b>Isolation</b><br>Hosted container or VM</p><p><b>State</b><br>Stop, archive, snapshot, fork</p><p><b>Network</b><br>Configurable</p><p><b>Meter</b><br>Usage-based resources</p></div>
<div class="product modal card"><div class="phead">Modal Sandbox</div><p><b>Best fit</b><br>Serverless + volumes, tunnels, GPUs</p><p><b>Isolation</b><br>Secure Modal runtime</p><p><b>State</b><br>Snapshots + volumes</p><p><b>Network</b><br>Explicit capabilities</p><p><b>Meter</b><br>Per-second resource maximum</p></div>
</div><div class="matrixNote">Published startup claims measure different operations, images, percentiles, regions, and warm-pool strategies. Treat them as references—not a league table.</div></div>""",
    """.matrix{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-top:40px}.product{height:570px;overflow:hidden}.phead{padding:19px 16px;color:white;font-size:20px;font-weight:760}.product p{margin:0;padding:16px;border-top:1px solid #dadce0;font-size:14px;line-height:1.42;color:#5f6368}.product b{color:#202124}.cloud .phead{background:#4285f4}.gke .phead{background:#34a853}.e2b .phead{background:#a142f4}.daytona .phead{background:#f9ab00}.modal .phead{background:#ea4335}.matrixNote{margin-top:20px;background:#202124;color:#e8eaed;border-radius:14px;padding:15px 20px;font-size:14px}""",
)

write(
    "cost-breakdown.html",
    "Reasonable monthly cost estimate",
    """<div class="canvas"><div class="eyebrow">Modeled cost · explicit assumptions</div><h1>A modest 1,000-review month: estimated $9.7954</h1><div class="sub">1,000 invocations · 30 active seconds · effective concurrency 2 · 3,000 input + 500 output tokens per review</div><div class="costgrid"><div class="donut"><div class="hole"><span>Total</span><b>$9.80</b><small>before free tier</small></div></div><div class="costrows"><div><i class="blueDot"></i><span>Gemini input</span><b>$4.500</b><em>45.94%</em></div><div><i class="purpleDot"></i><span>Gemini output</span><b>$4.500</b><em>45.94%</em></div><div><i class="greenDot"></i><span>Cloud Run compute</span><b>$0.795</b><em>8.12%</em></div><div><i class="yellowDot"></i><span>Cloud Run requests</span><b>$0.0004</b><em>0.004%</em></div></div></div><div class="insight"><b>Reasonable takeaway:</b> at this modest volume, the whole modeled workload is under $10/month before free tier. Tokens are still the largest meter, but the estimate no longer assumes 10,000 agent reviews.</div><div class="assume">Modeled, not measured billing · Gemini 3.5 Flash global Standard PayGo · Cloud Run 2 vCPU / 2 GiB · excludes builds, registry, logs, storage, egress, free tiers, and discounts</div></div>""",
    """.costgrid{display:grid;grid-template-columns:500px 1fr;gap:80px;align-items:center;margin-top:45px}.donut{width:430px;height:430px;border-radius:50%;background:conic-gradient(#4285f4 0 45.94%,#a142f4 45.94% 91.88%,#34a853 91.88% 99.996%,#f9ab00 99.996%);display:grid;place-items:center;box-shadow:0 16px 40px rgba(60,64,67,.15)}.hole{width:255px;height:255px;border-radius:50%;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center}.hole span{color:#5f6368;font-size:17px}.hole b{font-size:52px;letter-spacing:-2px}.hole small{color:#5f6368}.costrows>div{display:grid;grid-template-columns:20px 1fr 150px 90px;gap:14px;align-items:center;padding:22px 18px;border-bottom:1px solid #dadce0;font-size:18px}.costrows i{width:14px;height:14px;border-radius:50%}.costrows b{text-align:right;font-size:24px}.costrows em{text-align:right;color:#5f6368;font-style:normal}.blueDot{background:#4285f4}.purpleDot{background:#a142f4}.greenDot{background:#34a853}.yellowDot{background:#f9ab00}.insight{margin-top:32px;background:#e8f0fe;border-left:6px solid #4285f4;border-radius:0 14px 14px 0;padding:16px 20px;font-size:17px}.assume{margin-top:18px;color:#5f6368;font-size:13px}""",
)

# Focused screenshot annotations. These wrappers preserve the original pixels.
ANNOTATION_EXTRA = """.shot{position:absolute;left:0;top:0;width:1600px;height:900px}.box{position:absolute;border:5px solid #fbbc04;border-radius:14px;box-shadow:0 0 0 9999px rgba(0,0,0,.12)}.call{position:absolute;background:#fff;border:3px solid #4285f4;border-radius:16px;padding:15px 18px;font-size:17px;line-height:1.35;box-shadow:0 10px 30px rgba(0,0,0,.24)}.call b{display:block;color:#1967d2;font-size:20px;margin-bottom:5px}.arrow{position:absolute;height:4px;background:#4285f4;transform-origin:left center}.arrow:after{content:'';position:absolute;right:-2px;top:-7px;border-left:14px solid #4285f4;border-top:9px solid transparent;border-bottom:9px solid transparent}"""
write("annotated-security-probe.html","Annotated security probe", """<div style="position:relative;width:1600px;height:900px"><img class="shot" src="./screenshots/adk-web-security-probe.png"><div class="box" style="left:54px;top:530px;width:414px;height:340px"></div><div class="call" style="left:1070px;top:140px;width:450px"><b>Observed, not inferred</b>The selected FunctionResponse contains the raw environment, metadata, egress, root-overlay, and workspace results.</div><div class="arrow" style="left:1060px;top:285px;width:260px;transform:rotate(155deg)"></div></div>""", ANNOTATION_EXTRA)
write("annotated-failing-tests.html","Annotated failing tests", """<div style="position:relative;width:1600px;height:900px"><img class="shot" src="./screenshots/adk-web-failing-tests.png"><div class="box" style="left:272px;top:392px;width:770px;height:498px"></div><div class="call" style="left:1080px;top:170px;width:455px"><b>Failure is evidence</b>ADK preserves the complete pytest FunctionResponse: status, return code, host elapsed time, stdout, and traceback.</div><div class="arrow" style="left:1080px;top:330px;width:230px;transform:rotate(155deg)"></div></div>""", ANNOTATION_EXTRA)
write("annotated-tool-sequence.html","Annotated ADK tool sequence", """<div style="position:relative;width:1600px;height:900px"><img class="shot" src="./screenshots/adk-web-tool-sequence.png"><div class="box" style="left:500px;top:115px;width:410px;height:195px"></div><div class="box" style="left:500px;top:315px;width:430px;height:305px;border-color:#ea4335"></div><div class="box" style="left:500px;top:620px;width:430px;height:165px;border-color:#34a853"></div><div class="call" style="left:1030px;top:150px;width:455px"><b>1 · Establish trust boundary</b>start → inspect boundaries</div><div class="call" style="left:1030px;top:370px;width:455px;border-color:#ea4335"><b style="color:#c5221f">2 · Evidence-driven repair</b>failing test → generated patch → passing retest</div><div class="call" style="left:1030px;top:650px;width:455px;border-color:#34a853"><b style="color:#188038">3 · Export and clean up</b>snapshot → force delete</div></div>""", ANNOTATION_EXTRA)

print("generated deterministic blog visuals")
